app/models.py
from . import db
from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin


class User(db.Model, UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    firstname = db.Column(db.String(255), nullable=False)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    
class Place(db.Model):
    __tablename__ = 'places'
    place_id = db.Column(db.Integer, primary_key=True)
    city_name = db.Column(db.String(255), nullable=False)
    place_name = db.Column(db.String(255), nullable=False)

class Review(db.Model):
    __tablename__ = 'reviews'
    review_id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    place_id = db.Column(db.Integer, db.ForeignKey('places.place_id'), nullable=False)
    rating = db.Column(db.Float, nullable=False)
    review_text = db.Column(db.Text, nullable=False)
    review_date = db.Column(db.Date, nullable=False)
    raw_review = db.Column(db.Text, nullable=False)

app/__init__.py
from flask import Flask
# from .config import Config
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "database.db"

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] ='cnmu0V52TUq_Q0sqwBJBjw'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)
    
    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix = '/')
    app.register_blueprint(auth, url_prefix = '/')

    from .models import User

    create_database(app)

    # where should you redirect when login is required(eg itinerary page) and you r not logged in
    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    # telling flask how we load a user
    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))
        
    return app

def create_database(app):
    with app.app_context():  
        db.create_all()
        print('created database!')

app/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from . import db 
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import logout_user, login_required, login_user, current_user


auth = Blueprint('auth', __name__)

@auth.route('/login', methods = ['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

    # check if the user with the email exists
        user = User.query.filter_by(email = email).first()
        if user:
            if check_password_hash(user.password, password):
                # flash('logged in successfully', category='success')
                login_user(user, remember = True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again', category= 'error')
        else:
            flash('email does not exist', category = 'error')
    return render_template("login.html")

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('views.home'))

@auth.route('/signup',  methods = ['GET', 'POST'])
def signup():
    if request.method == 'POST':
        email = request.form.get('email')
        firstname = request.form.get('firstname')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        # define user
        new_user = User(email = email, firstname = firstname, password = generate_password_hash(password1, method = 'pbkdf2:sha256'))
        # add user to database
        db.session.add(new_user)
        db.session.commit()
        login_user(new_user, remember = True)
        # redirect to home page once user sign ups
        return redirect(url_for('views.home'))
    

# TO FLASH MESSAGE, THERE NEEDS TO BE A FUNC ADDED IN template.html
        # user = User.query.filter_by(email = email).first()
        # if user:
        #     flash('Email already exists', category=error)
        # if len(email) < 4:
        #     flash('Email must be greater than 4 characters.', category = 'error')
        # elif len(firstname) < 2:
        #     flash('First name must be greater than 1 character.', category='error')
        # elif password1 != password2:
        #     flash('Passwords don\'t match.', category='error')
        # elif len(password1) < 7:
        #     flash('Password must be at least 7 characters.', category='error')
        # else: *create a user*
        #     flash('account created!', category='success')
        
    return render_template("signup.html")

app/views.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user

views = Blueprint('views', __name__)

@views.route('/')
# @login_required
def home():
    return render_template("index.html")

@views.route('/itinerary_page')
@login_required
def itinerary_page():
    return render_template('itinerary_page.html')

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Path Planner</title>
    <link rel="stylesheet" href="../static/css/styles.css">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
</head>
<body>
    <header>
        <div class="logo">
            <a href=""><img src="{{ url_for('static', filename='images/logo-without-bg.png') }}" alt="Logo">
            </a>
        </div>
        <nav>
            <ul>
                <div class="non-auth-buttons">
                <li><button class="btn2 home-btn" onclick="location.href=''">Home</button></li>
                <li><button class="btn2 how-it-works-btn" onclick="location.href='#'">How It Works</button></li>
                </div>
                <div class="auth-buttons">
                {% if current_user.is_authenticated %}
                <li><button class="btn logout-btn" onclick="location.href='logout'">Log out</button></li>
                {% else %}
                <li><button class="btn login-btn" onclick="location.href='login'">Log In</button></li>
                <li><button class="btn signup-btn" onclick="location.href='signup'">Sign Up</button></li>
                {% endif %}
                </div>
            </ul>
        </nav>
    </header>
    
    <section class="banner">
        <h1>Embark on your Adventure</h1>
        <p>with your travel companion</p>
    </section>
    
    <section class="plan-itinerary">
        <h2>Plan your trip now!!</h2>
        <form id="itineraryForm">
            <label for="destination">Where do you wanna visit?</label>
            <input type="text" id="destination" name="destination" required>

            <label for="startDate">Start Date-</label>
            <input type="date" id="startDate" name="startDate" required>

            <label for="endDate">End Date-</label>
            <input type="date" id="endDate" name="endDate" required>

            <button type="submit" onclick="location.href='itinerary_page'">Plan Itinerary</button>
        </form>
    </section>

    <footer>
        <a href=""><img src="{{ url_for('static', filename='images/white-logo.png') }}"></a>
        <div class="footer-content">
            <p> &copy; 2024 Plan Path. All rights reserved.</p>
        </div>
        <ul class="social-media">
          <li><a href="https://gitlab.com/wanderers1/pathplan"><img src="{{ url_for('static', filename='images/gitlab-logo-500-removebg-preview.png') }}"></a></li>
        </ul>
    </footer>

    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
</body>
</html>

app/templates/itinerary_page.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link href="https://fonts.googleapis.com/css2?family=Pacifico&family=Ubuntu:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/itinerary_page/itinerary_page.css') }}">

  <script defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCXSwfxutGMziO5ZgPvglcdV8FlI0oKqgY&libraries=places"></script>
  <script type="module" src="{{ url_for('static', filename='js/index.js') }}"></script>

  <title>Trip Planner</title>
</head>

<body>

  <main class="main-container">

    <section class="planner-container">
        <header>
            <div class="logo">
                <a href="{{ url_for('views.home') }}"><img src="{{ url_for('static', filename='images/white-logo.png') }}" alt="Path Planner Logo"></a>
            </div>
        </header>
        <div class="planner-content">
            <div class="planner-box bucket">
                <div class="title"><p>Place Bucket</p></div>
                <div class="planner-list"></div>
            </div>
        </div>
    </section>

    <section class="place-container">
      <div class="place-overview">
        
      </div>
      <div id="place-num"></div>
      <div class="place-list"></div>
    </section>

    <section id="map"></section>
  </main>
</body>
</html>

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>
    <div class="container">
        <div class="signin-form">
            <h2>Login</h2>
            <form method="POST" action="{{ url_for('auth.login') }}">
                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="text" id="email" name="email" required>
                </div>

                <div class="form-group">
                    <label for="password">Password:</label>
                    <input type="password" id="password" name="password" required>
                </div>

                <div class="form-actions">
                    <a href="{{ url_for('auth.signup') }}" class="signup-link">New user? Sign Up</a>
                    <button type="submit">Sign In</button>
                </div>
            </form>
        </div>
        <div class="image-container">
            <img src="{{ url_for('static', filename='images/bgimg.png') }}" alt="background image">
        </div>
    </div>    
</body>
</html>

app/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign-Up</title>
    <link rel="stylesheet" href="../static/css/style.css">
</head>
<body>
    <div class="container">
        <div class="signup-form">
            <h2>Sign Up</h2>
            <form method = "POST">
                <div class="name-container">
                    <div class="form-group">
                        <label for="firstname">First Name:</label>
                        <input type="text" id="firstname" name="firstname" required>
                    </div>

                    <div class="form-group">
                        <label for="last-name">Last Name:</label>
                        <input type="text" id="last-name" name="last-name" required>
                    </div>
                </div>

                <div class="dob-city-container">
                    <div class="dob-container">
                        <label for="dob">Date of Birth:</label>
                        <input type="date" id="dob" name="dob" required>
                    </div>

                    <div class="city-container">
                        <label for="current-city">Current City:</label>
                        <select id="current-city" name="current-city" required>
                            <option value="" disabled selected>Select a city</option>
                            <option value="Delhi">Delhi</option>
                            <option value="Mumbai">Mumbai</option>
                            <option value="Kolkata">Kolkata</option>
                            <option value="Chennai">Chennai</option>
                            <option value="Bangalore">Bangalore</option>
                            <option value="Hyderabad">Hyderabad</option>
                            <option value="Ahmedabad">Ahmedabad</option>
                            <option value="Pune">Pune</option>
                            <option value="Jaipur">Jaipur</option>
                            <option value="Lucknow">Lucknow</option>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <label for="user-id">User ID:</label>
                    <input type="text" id="user-id" name="user-id" required>
                </div>

                <div class="form-group">
                    <label for="email-id">Email ID:</label>
                    <input type="email" id="email" name="email" required>
                </div>

                <div class="form-group">
                    <label for="password">Password:</label>
                    <input type="password" id="password1" name="password1" required>
                </div>

                <div class="form-group">
                    <label for="confirm-password">Confirm Password:</label>
                    <input type="password" id="password2" name="password2" required>
                </div>

                <div class="form-actions">
                    <a href="signin.html" class="signin-link">Already a user? Sign In</a>
                    <button type="submit">Register</button>
                </div>
            </form>
        </div>
        <div class="image-container">
            <img src="{{ url_for('static', filename='images/bgimg.png') }}" alt="background image">
        </div>
    </div>    
</body>
</html>